"""Allow_null_user_id_in_user_login_logs_table

Revision ID: 1c2bdb569923
Revises: 1ef48be23f6f
Create Date: 2025-06-23 10:10:52.751723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c2bdb569923'
down_revision = '1ef48be23f6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_login_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='用户ID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_login_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='用户ID')
    # ### end Alembic commands ###