"""Allow_null_user_id_in_user_login_logs

Revision ID: 1ef48be23f6f
Revises: 
Create Date: 2025-06-23 10:08:48.131643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef48be23f6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='用户ID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='用户ID')
    # ### end Alembic commands ###