"""add_page_function_column_to_system_logs

Revision ID: 2344aeaae0d9
Revises: a49c5a914034
Create Date: 2025-08-13 14:33:09.736161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2344aeaae0d9'
down_revision = 'a49c5a914034'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_logs', sa.Column('page_function', sa.String(length=200), nullable=True, comment='页面功能描述'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_logs', 'page_function')
    # ### end Alembic commands ###