"""add_enabled_and_started_at_to_diagnosis_tasks

Revision ID: a49c5a914034
Revises: 2fe413eafb6d
Create Date: 2025-08-11 12:23:30.687107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a49c5a914034'
down_revision = '2fe413eafb6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnosis_tasks', sa.Column('enabled', sa.Boolean(), nullable=True, comment='是否启用'))
    op.add_column('diagnosis_tasks', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='任务开始时间'))
    
    # Set default values for existing records
    op.execute("UPDATE diagnosis_tasks SET enabled = true WHERE enabled IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagnosis_tasks', 'started_at')
    op.drop_column('diagnosis_tasks', 'enabled')
    # ### end Alembic commands ###