"""Add template_id to diagnosis_tasks

Revision ID: f59228b0d234
Revises: d836fcc93aa6
Create Date: 2025-07-11 00:46:50.988036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f59228b0d234'
down_revision = 'd836fcc93aa6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnosis_tasks', sa.Column('template_id', sa.Integer(), nullable=True, comment='诊断模板ID'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagnosis_tasks', 'template_id')
    # ### end Alembic commands ###